- "group": "COP"
  "key": ["st_ref_cop", "abc_ref_cop", "act_cop" ]
  "name": ['ST ref COP','ABC ref COP','act COP']
  "index": [[0,1], [0,0], [0,0]]
# "index": [[2,3], [0,0], [0,0]]

- "group": "Fz"
  "key": ["rmfo_off_rfsensor", "rmfo_off_lfsensor", "rmfo_off_rhsensor", "rmfo_off_lhsensor"]
  "index": [[2],[2],[2],[2]]

- "group": "zmp"
  "key": ["abc_zmp", "st_originRefZmp", "st_originNewZmp", "st_originActZmp"]
  "index": [[0,1], [0,1], [0,1], [0,1]]