'sh_qOut':
  'func': 'plot_rad2deg'
  'log': ['sh_qOut']
  'index': ['0:']
'abc_q':
  'func': 'plot_rad2deg'
  'log': ['abc_q']
  'index': ['10:']
'st_q':
  'func': 'plot_rad2deg'
  'log': ['st_q']
  'index': ['0:']
'RobotHardware0_q':
  'func': 'plot_rad2deg'
  'log': ['RobotHardware0_q']
  'index': ['0:']
'rh_st_diff':
  'func': 'plot_rh_q_st_q'
  'log': ['RobotHardware0_q','st_q']
  'index': ['0:','0:']
'abs_enc_diff':
  'func': 'plot_abs_enc'
  'log': ['RobotHardware0_servoState','RobotHardware0_servoState']
  'index': ['0:','0:']
'sh_rfsensorOut':
  'log': ['sh_rfsensorOut']
  'index': ['0:6']
'RobotHardware0_rfsensor':
  'log': ['RobotHardware0_rfsensor']
  'index': ['0:6']
'rmfo_off_rfsensor':
  'log': ['rmfo_off_rfsensor']
  'index': ['0:6']
"current":
  'log': ['RobotHardware0_servoState']
  'func': 'plot_current'
  'index': [[0,1,2,3,4,5]]
# todo
# imu is not check x,y,z
"imu_x":
  "log": ['RobotHardware0_gsensor','RobotHardware0_gyrometer']
  "func": 'plot_imu'
  "index": [[0,1],[0,1]]
"imu_y":
  "log": ['RobotHardware0_gsensor','RobotHardware0_gyrometer']
  "func": 'plot_imu'
  "index": [[0,1],[0,1]]
"imu_z":
  "log": ['RobotHardware0_gsensor','RobotHardware0_gyrometer']
  "func": 'plot_imu'
  "index": [[0,1],[0,1]]

"motor_temp":
  "log": ['RobotHardware0_servoState']
  "func": 'plot_motor_temp'
  "index": [[0,1,2,3,4,5]]

'motor_outer_temp':
  "log": ['RobotHardware0_servoState']
  "func": 'plot_motor_outer_temp'
  "index": [[0,1,2,3,4,5]]

"comp":
  "log": ['st_allEEComp']
  "func": 'plot_comp'
  "index": [[0,1,2, 3, 4, 5]]

"watt":
  "log": ['RobotHardware0_dq','RobotHardware0_tau']
  "func": 'plot_watt'
  "index": [[0,1,2,3,4,5],[0,1,2,3,4,5]]

"ServoState":
  "log": ['RobotHardware0_servoState']
  "func": 'plot_servostate'
  "index": [[0,1,2,3,4,5]]

"12V":
  "log": ['RobotHardware0_servoState']
  "func": 'plot_12V'
  "index": [[0,1,2,3,4,5]]

"80V":
  "log": ['RobotHardware0_servoState']
  "func": 'plot_80V'
  "index": [[0,1,2,3,4,5]]

