"joint_angle":
  "log": ['sh_qOut', 'ic_q', 'abc_q', 'st_q', 'RobotHardware0_q']
  "field": [[0,1,2,3,4,5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"right_foot_force":
  "log": ['sh_rfsensorOut', 'RobotHardware0_rfsensor', 'rmfo_off_rfsensor']
  "field": [[0,1,2,3,4,5]]

"left_foot_force":
  "log": ['sh_lfsensorOut', 'RobotHardware0_lfsensor', 'rmfo_off_lfsensor']
  "field": [[0,1,2,3,4,5]]

"right_hand_force":
  "log": ['sh_rhsensorOut', 'RobotHardware0_rhsensor', 'rmfo_off_rhsensor']
  "field": [[0,1,2,3,4,5]]

"left_hand_force":
  "log": ['sh_lhsensorOut', 'RobotHardware0_lhsensor', 'rmfo_off_lhsensor']
  "field": [[0,1,2,3,4,5]]

# "attitude":
#   "log": ['sh_baseRpyOut', 'st_actBaseRpy', 'st_currentBaseRpy', 'kf_rpy']
#   "field": [[0,1,2]]

# "imu":
#   "log": ['RobotHardware0_gsensor', 'RobotHardware0_gyrometer']
#   "field": [[0,1,2]]

# "torque":
#   "log": ['RobotHardware0_tau']
#   "field": [[0,1,2,3,4,5], [6,7,8,9,10,11]]
