"joint_velocity":
  "log": ['RobotHardware0_dq']
  # "field": [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
  "field": [[8, 9]]
"tracking":
  "log": ['st_q', 'RobotHardware0_q', 'RobotHardware0_servoState']
  # "field": [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
  "field": [[8, 9]]
